package com.test.model;

import java.io.Serializable;
import java.util.Date;

public class QtActivity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.publicUserId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer publicuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.theme
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.content
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.contact
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.activityTypeId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer activitytypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.time
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.startTime
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.endTime
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.img
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.link
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.limitNumber
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer limitnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.address
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_activity.sum
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.id
     *
     * @return the value of qt_activity.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.id
     *
     * @param id the value for qt_activity.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.publicUserId
     *
     * @return the value of qt_activity.publicUserId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getPublicuserid() {
        return publicuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.publicUserId
     *
     * @param publicuserid the value for qt_activity.publicUserId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setPublicuserid(Integer publicuserid) {
        this.publicuserid = publicuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.theme
     *
     * @return the value of qt_activity.theme
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.theme
     *
     * @param theme the value for qt_activity.theme
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.content
     *
     * @return the value of qt_activity.content
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.content
     *
     * @param content the value for qt_activity.content
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.contact
     *
     * @return the value of qt_activity.contact
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.contact
     *
     * @param contact the value for qt_activity.contact
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.activityTypeId
     *
     * @return the value of qt_activity.activityTypeId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getActivitytypeid() {
        return activitytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.activityTypeId
     *
     * @param activitytypeid the value for qt_activity.activityTypeId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setActivitytypeid(Integer activitytypeid) {
        this.activitytypeid = activitytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.time
     *
     * @return the value of qt_activity.time
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.time
     *
     * @param time the value for qt_activity.time
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.startTime
     *
     * @return the value of qt_activity.startTime
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.startTime
     *
     * @param starttime the value for qt_activity.startTime
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.endTime
     *
     * @return the value of qt_activity.endTime
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.endTime
     *
     * @param endtime the value for qt_activity.endTime
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.img
     *
     * @return the value of qt_activity.img
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.img
     *
     * @param img the value for qt_activity.img
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.link
     *
     * @return the value of qt_activity.link
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.link
     *
     * @param link the value for qt_activity.link
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.limitNumber
     *
     * @return the value of qt_activity.limitNumber
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getLimitnumber() {
        return limitnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.limitNumber
     *
     * @param limitnumber the value for qt_activity.limitNumber
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setLimitnumber(Integer limitnumber) {
        this.limitnumber = limitnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.address
     *
     * @return the value of qt_activity.address
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.address
     *
     * @param address the value for qt_activity.address
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_activity.sum
     *
     * @return the value of qt_activity.sum
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_activity.sum
     *
     * @param sum the value for qt_activity.sum
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }
}