package com.test.model;

import java.util.ArrayList;
import java.util.List;

public class QtPartinExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public QtPartinExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActivityidIsNull() {
            addCriterion("activityId is null");
            return (Criteria) this;
        }

        public Criteria andActivityidIsNotNull() {
            addCriterion("activityId is not null");
            return (Criteria) this;
        }

        public Criteria andActivityidEqualTo(Integer value) {
            addCriterion("activityId =", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotEqualTo(Integer value) {
            addCriterion("activityId <>", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidGreaterThan(Integer value) {
            addCriterion("activityId >", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("activityId >=", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidLessThan(Integer value) {
            addCriterion("activityId <", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidLessThanOrEqualTo(Integer value) {
            addCriterion("activityId <=", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidIn(List<Integer> values) {
            addCriterion("activityId in", values, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotIn(List<Integer> values) {
            addCriterion("activityId not in", values, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidBetween(Integer value1, Integer value2) {
            addCriterion("activityId between", value1, value2, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotBetween(Integer value1, Integer value2) {
            addCriterion("activityId not between", value1, value2, "activityid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridIsNull() {
            addCriterion("publicUserId is null");
            return (Criteria) this;
        }

        public Criteria andPublicuseridIsNotNull() {
            addCriterion("publicUserId is not null");
            return (Criteria) this;
        }

        public Criteria andPublicuseridEqualTo(Integer value) {
            addCriterion("publicUserId =", value, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridNotEqualTo(Integer value) {
            addCriterion("publicUserId <>", value, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridGreaterThan(Integer value) {
            addCriterion("publicUserId >", value, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("publicUserId >=", value, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridLessThan(Integer value) {
            addCriterion("publicUserId <", value, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridLessThanOrEqualTo(Integer value) {
            addCriterion("publicUserId <=", value, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridIn(List<Integer> values) {
            addCriterion("publicUserId in", values, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridNotIn(List<Integer> values) {
            addCriterion("publicUserId not in", values, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridBetween(Integer value1, Integer value2) {
            addCriterion("publicUserId between", value1, value2, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andPublicuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("publicUserId not between", value1, value2, "publicuserid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidIsNull() {
            addCriterion("activityTypeId is null");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidIsNotNull() {
            addCriterion("activityTypeId is not null");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidEqualTo(Integer value) {
            addCriterion("activityTypeId =", value, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidNotEqualTo(Integer value) {
            addCriterion("activityTypeId <>", value, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidGreaterThan(Integer value) {
            addCriterion("activityTypeId >", value, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("activityTypeId >=", value, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidLessThan(Integer value) {
            addCriterion("activityTypeId <", value, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidLessThanOrEqualTo(Integer value) {
            addCriterion("activityTypeId <=", value, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidIn(List<Integer> values) {
            addCriterion("activityTypeId in", values, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidNotIn(List<Integer> values) {
            addCriterion("activityTypeId not in", values, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidBetween(Integer value1, Integer value2) {
            addCriterion("activityTypeId between", value1, value2, "activitytypeid");
            return (Criteria) this;
        }

        public Criteria andActivitytypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("activityTypeId not between", value1, value2, "activitytypeid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qt_partin
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 20:45:38 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}