package com.test.model;

import java.io.Serializable;

public class QtPartin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_partin.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_partin.activityId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_partin.userId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_partin.publicUserId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer publicuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_partin.activityTypeId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer activitytypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qt_partin
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_partin.id
     *
     * @return the value of qt_partin.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_partin.id
     *
     * @param id the value for qt_partin.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_partin.activityId
     *
     * @return the value of qt_partin.activityId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_partin.activityId
     *
     * @param activityid the value for qt_partin.activityId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_partin.userId
     *
     * @return the value of qt_partin.userId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_partin.userId
     *
     * @param userid the value for qt_partin.userId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_partin.publicUserId
     *
     * @return the value of qt_partin.publicUserId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getPublicuserid() {
        return publicuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_partin.publicUserId
     *
     * @param publicuserid the value for qt_partin.publicUserId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setPublicuserid(Integer publicuserid) {
        this.publicuserid = publicuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_partin.activityTypeId
     *
     * @return the value of qt_partin.activityTypeId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getActivitytypeid() {
        return activitytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_partin.activityTypeId
     *
     * @param activitytypeid the value for qt_partin.activityTypeId
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setActivitytypeid(Integer activitytypeid) {
        this.activitytypeid = activitytypeid;
    }
}