package com.test.model;

import java.io.Serializable;

public class QtUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_user.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_user.name
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_user.password
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_user.sex
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_user.contact
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qt_user.address
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qt_user
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_user.id
     *
     * @return the value of qt_user.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_user.id
     *
     * @param id the value for qt_user.id
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_user.name
     *
     * @return the value of qt_user.name
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_user.name
     *
     * @param name the value for qt_user.name
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_user.password
     *
     * @return the value of qt_user.password
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_user.password
     *
     * @param password the value for qt_user.password
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_user.sex
     *
     * @return the value of qt_user.sex
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_user.sex
     *
     * @param sex the value for qt_user.sex
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_user.contact
     *
     * @return the value of qt_user.contact
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_user.contact
     *
     * @param contact the value for qt_user.contact
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qt_user.address
     *
     * @return the value of qt_user.address
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qt_user.address
     *
     * @param address the value for qt_user.address
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }
}