package com.test.dao;

import com.test.model.QtActivity;
import com.test.model.QtActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QtActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int countByExample(QtActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int deleteByExample(QtActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int insert(QtActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int insertSelective(QtActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    List<QtActivity> selectByExample(QtActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    QtActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") QtActivity record, @Param("example") QtActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int updateByExample(@Param("record") QtActivity record, @Param("example") QtActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int updateByPrimaryKeySelective(QtActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qt_activity
     *
     * @mbggenerated Fri May 13 20:45:38 CST 2016
     */
    int updateByPrimaryKey(QtActivity record);
}